trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Build.Counter: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]

steps:

- task: PowerShell@2
  displayName: Set Build Number
  inputs:
    filePath: 'build/SetBuildNumber.ps1'

- task: PowerShell@2
  displayName: Apply Version To Assemblies
  inputs:
    filePath: 'build/ApplyVersionToAssemblies.ps1'

- task: NuGetToolInstaller@1
  displayName: Instal NuGet Tools

- task: NuGetCommand@2
  displayName: NuGet Restore
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: Create Archive
  inputs:
    rootFolderOrFile: 'src/HtmlToPdf/bin/$(buildConfiguration)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlToPdf-v$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/HtmlToPdf-v$(Build.BuildNumber).zip'
    artifactName: 'HtmlToPdf-v$(Build.BuildNumber)'
    publishLocation: 'Container'

- task: VSTest@2
  displayName: Run Tests
  inputs:
    runSettingsFile: 'src/RunSettings.runsettings'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True

- task: GitHubRelease@0
  displayName: Publish GitHub Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceVersionMessage'], '[Release]'))
  inputs:
    gitHubConnection: release
    repositoryName: '$(Build.Repository.Name)' 
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'
    assets: '$(Build.ArtifactStagingDirectory)/*'
    isDraft: true
    addChangeLog: true